---
title: "Bioassay case study"
format: 
    html:
        embed-resources: true
---

# Introduction

## Load packages
```{r}
library(rprojroot)
root <- has_file(".Bayesian-Workflow-root")$make_fix_file()
library(cmdstanr)
library(brms)
options(brms.backend = "cmdstanr", mc.cores = 4)
library(posterior)
library(ggplot2)
library(ggdist)
library(dplyr)
library(tidyr)
library(bayesplot)
theme_set(bayesplot::theme_default(base_family = "sans", base_size = 16))
library(marginaleffects)

print_stan_file <- function(file) {
  code <- readLines(file)
  if (isTRUE(getOption("knitr.in.progress")) &
        identical(knitr::opts_current$get("results"), "asis")) {
    # In render: emit as-is so Pandoc/Quarto does syntax highlighting
    block <- paste0("```stan", "\n", paste(code, collapse = "\n"), "\n", "```")
    knitr::asis_output(block)
  } else {
    writeLines(code)
  }
}
```
# Bioassay data

```{r}
df_bioassay <- read.csv("data/bioassay.csv")
```
Data plotted with base R
```{r}
with(df_bioassay,
plot(dose, deaths, xlab = "dose log(g/ml)", ylab = "# of deaths", pch = 19, cex = 1.5, bty = "l"))
```

Data plotted with ggplot

```{r}
df_bioassay |> 
    ggplot(aes(x = dose, y = deaths)) +
    geom_point(size = 3) +
    labs(x = "Dose log(g/ml)", y = "# of deaths")
```

Data as list for CmdStanR

```{r}
bioassay_data <- with(df_bioassay,
list(J = nrow(df_bioassay),
x = dose,
n = batch_size,
y = deaths))

bioassay_data
```

```{r}
print_stan_file(root("bioassay0.stan"))
```
# Stan models and inference

Stan model 0 (without priors)

```{r}
mod0 <- cmdstan_model("bioassay0.stan", pedantic=TRUE)
```

Printing and graphing the fitted model

```{r}
fit0 <- mod0$sample(data=bioassay_data, refresh=0)
print(fit0)
```
## Model with prior

```{r}
mod1 <- cmdstan_model("bioassay1.stan", pedantic=TRUE)
```
## Printing and graphing the fitted model
```{r}
fit1 <- mod1$sample(data=bioassay_data, refresh=0)
print(fit1)
```

```{r}
draws1 <- fit1$draws(format="df")
```

```{r}
par(mar=c(3,3,1,1), mgp=c(1.5,.5,0), tck=-.01)
with(df_bioassay, 
plot(dose, deaths/batch_size, xlab="Dose", ylab="Pr (death)", pch=19, cex=1.5, bty="l"))
invlogit <- plogis
for (s in sample(nrow(draws1), 20)) {
  curve(invlogit(draws1$a[s] + draws1$b[s] * x), col="red", lwd=0.5, add=TRUE)
}
curve(invlogit(mean(draws1$a) + mean(draws1$b) * x), col="blue", lwd=2, add=TRUE)
```

```{r}
draws1 |>
  resample_draws(ndraws = 20) |>
  expand_grid(x=seq(-1, 1, length = 100)) |>
  mutate(y = plogis(a + b * x)) |>
  ggplot() +
  geom_point(data = df_bioassay, aes(x = dose, y = deaths / batch_size), size = 3) +
  geom_line(aes(x = x, y = y, group = .draw), alpha = .5, color = "red") +
  geom_function(fun = \(x) plogis(mean(draws1$a) + mean(draws1$b)*x),
                color = "blue",
                linewidth = 1) +
  labs(x = "Dose log(g/ml)", y = "Pr(death)")
```